// Catálogo original de MELNE.
// Se usa para importar los productos a Supabase la primera vez
// y como respaldo si la base de datos no está disponible.
window.CATALOGO_INICIAL = [
    {"codigo":"MEL-H001","nombre":"212 AQUA","categoria":"Hombre","descripcion":"Amaderado, calido especiado, citrico","precio":80000,"imagen":"imagenes/hombre/212-aqua.jpg"},
    {"codigo":"MEL-H002","nombre":"212 BLACK","categoria":"Hombre","descripcion":"Aromatico, avainillado, especiado suave","precio":80000,"imagen":"imagenes/hombre/212-black.jpg"},
    {"codigo":"MEL-H003","nombre":"212 RED","categoria":"Hombre","descripcion":"Dulce, aromático, fresco especiado","precio":80000,"imagen":"imagenes/hombre/212-red.jpg"},
    {"codigo":"MEL-H004","nombre":"212 HEROES","categoria":"Hombre","descripcion":"Aromático, herbal, afrutado","precio":80000,"imagen":"imagenes/hombre/212-heroes.jpg"},
    {"codigo":"MEL-H005","nombre":"CH MEN","categoria":"Hombre","descripcion":"Cuero, dulce, avainillado","precio":80000,"imagen":"imagenes/hombre/ch-men.jpg"},
    {"codigo":"MEL-H006","nombre":"212 VIP","categoria":"Hombre","descripcion":"Aromático, vodka, cálido especiado","precio":80000,"imagen":"imagenes/hombre/212-vip.jpg"},
    {"codigo":"MEL-H007","nombre":"212 NYC","categoria":"Hombre","descripcion":"Cítrico, verde, cálido especiado","precio":80000,"imagen":"imagenes/hombre/212-nyc.jpg"},
    {"codigo":"MEL-H008","nombre":"MILLON ROYAL","categoria":"Hombre","descripcion":"Cálido especiado, aromatico, ambar","precio":80000,"imagen":"imagenes/hombre/millon-royal.jpg"},
    {"codigo":"MEL-H009","nombre":"ONE MILLION","categoria":"Hombre","descripcion":"Cálido especiado, canela, citrico","precio":80000,"imagen":"imagenes/hombre/one-million.jpg"},
    {"codigo":"MEL-H010","nombre":"MILLON PRIVE","categoria":"Hombre","descripcion":"Calido especiado, canela, dulce","precio":80000,"imagen":"imagenes/hombre/millon-prive.jpg"},
    {"codigo":"MEL-H011","nombre":"MILLON LUCKY","categoria":"Hombre","descripcion":"Amaderado, nueces, dulce","precio":80000,"imagen":"imagenes/hombre/millon-lucky.jpg"},
    {"codigo":"MEL-H012","nombre":"INVICTUS","categoria":"Hombre","descripcion":"Cítrico, marino, aromático","precio":80000,"imagen":"imagenes/hombre/invictus.jpg"},
    {"codigo":"MEL-H013","nombre":"INVICTUS LEGEND","categoria":"Hombre","descripcion":"Marino, aromático, fresco especiado","precio":80000,"imagen":"imagenes/hombre/invictus-legend.jpg"},
    {"codigo":"MEL-H014","nombre":"INVICTUS VICTORY","categoria":"Hombre","descripcion":"Ámbar, avainillado, dulce","precio":80000,"imagen":"imagenes/hombre/invictus-victory.jpg"},
    {"codigo":"MEL-H015","nombre":"VICTORY ELIXIR","categoria":"Hombre","descripcion":"Avainillado, ámbar, fresco especiado","precio":80000,"imagen":"imagenes/hombre/victory-elixir.jpg"},
    {"codigo":"MEL-H016","nombre":"INVICTUS INTENSE","categoria":"Hombre","descripcion":"Ámbar, fresco especiado, whisky","precio":80000,"imagen":"imagenes/hombre/invictus-intense.jpg"},
    {"codigo":"MEL-H017","nombre":"INVICTUS PARFUM","categoria":"Hombre","descripcion":"Almizclado, aromático, marino","precio":80000,"imagen":"imagenes/hombre/invictus-parfum.jpg"},
    {"codigo":"MEL-H018","nombre":"BLACK XS","categoria":"Hombre","descripcion":"Dulce, cálido especiado, cítrico","precio":80000,"imagen":"imagenes/hombre/black-xs.jpg"},
    {"codigo":"MEL-H019","nombre":"BLACK XS L'EXCES","categoria":"Hombre","descripcion":"Citrico, amaderado, ambar","precio":80000,"imagen":"imagenes/hombre/black-xs-exces.jpg"},
    {"codigo":"MEL-H020","nombre":"L'APHRODISIAQUE","categoria":"Hombre","descripcion":"Dulce, amielado, calido especiado","precio":80000,"imagen":"imagenes/hombre/l-aphrodisiaque.jpg"},
    {"codigo":"MEL-H021","nombre":"PHANTOM","categoria":"Hombre","descripcion":"Citrico, avainillado, lavanda","precio":80000,"imagen":"imagenes/hombre/phantom.jpg"},
    {"codigo":"MEL-H022","nombre":"PHANTOM PARFUM","categoria":"Hombre","descripcion":"Aromatico, avainillado, calido especiado","precio":80000,"imagen":"imagenes/hombre/phantom-parfum.jpg"},
    {"codigo":"MEL-H023","nombre":"PURE XS","categoria":"Hombre","descripcion":"Dulce, avainillado, Calido especiado","precio":80000,"imagen":"imagenes/hombre/pure-xs.jpg"},
    {"codigo":"MEL-H024","nombre":"HUGO RED","categoria":"Hombre","descripcion":"Afrutados, dulce, verde","precio":80000,"imagen":"imagenes/hombre/hugo-red.jpg"},
    {"codigo":"MEL-H025","nombre":"HUGO MAN","categoria":"Hombre","descripcion":"Amaderado, aromático, conífera","precio":80000,"imagen":"imagenes/hombre/hugo-man.jpg"},
    {"codigo":"MEL-H026","nombre":"JUST DIFFERENT","categoria":"Hombre","descripcion":"Verde, aromático, fresco especiado","precio":80000,"imagen":"imagenes/hombre/just-different.jpg"},
    {"codigo":"MEL-H027","nombre":"BOSS UNLIMITED","categoria":"Hombre","descripcion":"Verde, afrutados, dulce","precio":80000,"imagen":"imagenes/hombre/boss-unlimited.jpg"},
    {"codigo":"MEL-H028","nombre":"BOSS NIGHT","categoria":"Hombre","descripcion":"Amaderado, Violeta, atalcado","precio":80000,"imagen":"imagenes/hombre/boss-night.jpg"},
    {"codigo":"MEL-H029","nombre":"BOSS BOTTLED","categoria":"Hombre","descripcion":"Amaderado, afrutado, avainillado","precio":80000,"imagen":"imagenes/hombre/boss-bottled.jpg"},
    {"codigo":"MEL-H030","nombre":"LACOSTE BLEU","categoria":"Hombre","descripcion":"Aromático, cítrico, fresco","precio":80000,"imagen":"imagenes/hombre/lacoste-bleu.jpg"},
    {"codigo":"MEL-H031","nombre":"LACOSTE RED","categoria":"Hombre","descripcion":"Amaderado, afrutados, verde","precio":80000,"imagen":"imagenes/hombre/lacoste-red.jpg"},
    {"codigo":"MEL-H032","nombre":"LACOSTE WHITE","categoria":"Hombre","descripcion":"Amaderado, cítrico, aromático","precio":80000,"imagen":"imagenes/hombre/lacoste-white.jpg"},
    {"codigo":"MEL-H033","nombre":"LACOSTE NOIR","categoria":"Hombre","descripcion":"Amaderado, aromático, ozónico","precio":80000,"imagen":"imagenes/hombre/lacoste-noir.jpg"},
    {"codigo":"MEL-H034","nombre":"LACOSTE ROUGE","categoria":"Hombre","descripcion":"Calido especiado, tropical, afrutado","precio":80000,"imagen":"imagenes/hombre/lacoste-rouge.jpg"},
    {"codigo":"MEL-H035","nombre":"LACOSTE GREEN","categoria":"Hombre","descripcion":"Citrico, aromatico, fresco especiado","precio":80000,"imagen":"imagenes/hombre/lacoste-green.jpg"},
    {"codigo":"MEL-H036","nombre":"EROS FLAME","categoria":"Hombre","descripcion":"Cítrico, avainillado, aromático","precio":80000,"imagen":"imagenes/hombre/eros-flame.jpg"},
    {"codigo":"MEL-H037","nombre":"EROS VERSACE","categoria":"Hombre","descripcion":"Avainillado, aromático, verde","precio":80000,"imagen":"imagenes/hombre/eros-versace.jpg"},
    {"codigo":"MEL-H038","nombre":"EROS ENERGY","categoria":"Hombre","descripcion":"Cítrico, aromático, limón","precio":80000,"imagen":"imagenes/hombre/eros-energy.jpg"},
    {"codigo":"MEL-H039","nombre":"DYLAN BLUE","categoria":"Hombre","descripcion":"Ámbar, cítrico, fresco","precio":80000,"imagen":"imagenes/hombre/dylan-blue.jpg"},
    {"codigo":"MEL-H040","nombre":"KING","categoria":"Hombre","descripcion":"Aromático, amaderado, cálido","precio":80000,"imagen":"imagenes/hombre/king.jpg"},
    {"codigo":"MEL-H041","nombre":"THE ONE","categoria":"Hombre","descripcion":"Cálido especiado, ámbar, tabaco","precio":80000,"imagen":"imagenes/hombre/the-one.jpg"},
    {"codigo":"MEL-H042","nombre":"LIGHT BLUE","categoria":"Hombre","descripcion":"Fresco especiado, ozónico, citrico","precio":80000,"imagen":"imagenes/hombre/light-blue.jpg"},
    {"codigo":"MEL-H043","nombre":"ULTRA-MALE","categoria":"Hombre","descripcion":"Avainillado, afrutados, dulce","precio":80000,"imagen":"imagenes/hombre/ultra-male.jpg"},
    {"codigo":"MEL-H044","nombre":"LE MALE","categoria":"Hombre","descripcion":"Avainillado, aromático, fresco","precio":80000,"imagen":"imagenes/hombre/le-male.jpg"},
    {"codigo":"MEL-H045","nombre":"LE MALE ELIXIR","categoria":"Hombre","descripcion":"Cálida, dulce, sensual","precio":95000,"imagen":"imagenes/hombre/le-male-elixir.jpg"},
    {"codigo":"MEL-H046","nombre":"ULTRA MALE","categoria":"Hombre","descripcion":"Dulce, intensa, seductora","precio":95000,"imagen":"imagenes/hombre/ultra-male-plus.jpg"},
    {"codigo":"MEL-H047","nombre":"LE BEAU LE PARFUM","categoria":"Hombre","descripcion":"Tropical, dulce, coco","precio":95000,"imagen":"imagenes/hombre/le-beau-parfum.jpg"},
    {"codigo":"MEL-H048","nombre":"BAHARARA KING","categoria":"Hombre","descripcion":"Dulce, fresco, ambarado","precio":100000,"imagen":"imagenes/hombre/baharara-king.jpg"},
    {"codigo":"MEL-H049","nombre":"ERBA PURA","categoria":"Hombre","descripcion":"Frutal, dulce, fresca","precio":110000,"imagen":"imagenes/hombre/erba-pura.jpg"},
    {"codigo":"MEL-H050","nombre":"LE BEAU","categoria":"Hombre","descripcion":"Coco, avainillado, dulce","precio":80000,"imagen":"imagenes/hombre/le-beau.jpg"},
    {"codigo":"MEL-H051","nombre":"LE BEAU LE PARFUM","categoria":"Hombre","descripcion":"Dulce, amaderado, coco","precio":80000,"imagen":"imagenes/hombre/le-beau-le-parfum.jpg"},
    {"codigo":"MEL-H052","nombre":"LE MALE PARFUM","categoria":"Hombre","descripcion":"Calido especiado, avainillado, aromatico","precio":80000,"imagen":"imagenes/hombre/le-male-parfum.jpg"},
    {"codigo":"MEL-H053","nombre":"SCANDAL","categoria":"Hombre","descripcion":"Caramelo, aromático, dulce","precio":80000,"imagen":"imagenes/hombre/scandal.jpg"},
    {"codigo":"MEL-H054","nombre":"LEGEND SPIRIT","categoria":"Hombre","descripcion":"Cítrico, acuático, almizclado","precio":80000,"imagen":"imagenes/hombre/legend-spirit.jpg"},
    {"codigo":"MEL-H055","nombre":"LEGEND","categoria":"Hombre","descripcion":"Afrutados, dulce, aromático","precio":80000,"imagen":"imagenes/hombre/legend.jpg"},
    {"codigo":"MEL-H056","nombre":"AVENTUS","categoria":"Hombre","descripcion":"Afrutado, cuero, amaderado","precio":80000,"imagen":"imagenes/hombre/aventus.jpg"},
    {"codigo":"MEL-H057","nombre":"SILVER","categoria":"Hombre","descripcion":"Verde, cítrico, afrutados","precio":80000,"imagen":"imagenes/hombre/silver.jpg"},
    {"codigo":"MEL-H058","nombre":"360 BLUE","categoria":"Hombre","descripcion":"Aromático, amaderado, fresco","precio":80000,"imagen":"imagenes/hombre/360-blue.jpg"},
    {"codigo":"MEL-H059","nombre":"BLEU DE CHANEL","categoria":"Hombre","descripcion":"Avainillado, amaderado, atalcado","precio":80000,"imagen":"imagenes/hombre/bleu-de-chanel.jpg"},
    {"codigo":"MEL-H060","nombre":"FARENHEIT","categoria":"Hombre","descripcion":"Cuero, amaderado, ozonico","precio":80000,"imagen":"imagenes/hombre/farenheit.jpg"},
    {"codigo":"MEL-H061","nombre":"SAUVAGE","categoria":"Hombre","descripcion":"fresco especiado, ambar, citrico","precio":80000,"imagen":"imagenes/hombre/sauvage.jpg"},
    {"codigo":"MEL-H062","nombre":"MOSCHINO TOY PEARL","categoria":"Hombre","descripcion":"Citrico, aromatico, almizcado","precio":80000,"imagen":"imagenes/hombre/moschino-toy-pearl.jpg"},
    {"codigo":"MEL-H063","nombre":"TOY BOY","categoria":"Hombre","descripcion":"Rosas, florales, almizcado","precio":80000,"imagen":"imagenes/hombre/toy-boy.jpg"},
    {"codigo":"MEL-H064","nombre":"ASAD","categoria":"Hombre","descripcion":"Calido especiado, ambar, avainillado","precio":80000,"imagen":"imagenes/hombre/asad.jpg"},
    {"codigo":"MEL-H065","nombre":"ASAD BOURBON","categoria":"Hombre","descripcion":"Avainillado, cacao, aromático","precio":80000,"imagen":"imagenes/hombre/asad-bourbon.jpg"},
    {"codigo":"MEL-H066","nombre":"ASAD ZANZIBAR","categoria":"Hombre","descripcion":"Iris, atalcado, avainillado","precio":80000,"imagen":"imagenes/hombre/asad-zanzibar.jpg"},
    {"codigo":"MEL-H067","nombre":"ASAD ELIXIR","categoria":"Hombre","descripcion":"Especiada, ambarada, poderosa","precio":80000,"imagen":"imagenes/hombre/asad-elixir.jpg"},
    {"codigo":"MEL-H068","nombre":"OUD FOR GLORY","categoria":"Hombre","descripcion":"Oud, cálido, especiado","precio":80000,"imagen":"imagenes/hombre/oud-for-glory.jpg"},
    {"codigo":"MEL-H069","nombre":"OUD FOR GLORY ","categoria":"Hombre","descripcion":"Oud, cálido, especiado","precio":100000,"imagen":"imagenes/hombre/oud-for-glory-20.jpg"},
    {"codigo":"MEL-H070","nombre":"HONOR Y GLORIA","categoria":"Hombre","descripcion":"Dulce, cálido especiado, avainillado","precio":80000,"imagen":"imagenes/hombre/honor-y-gloria.jpg"},
    {"codigo":"MEL-H071","nombre":"HONOR Y GLORIA ","categoria":"Hombre","descripcion":"Dulce, cálido especiado, avainillado","precio":100000,"imagen":"imagenes/hombre/honor-y-gloria-20.jpg"},
    {"codigo":"MEL-H072","nombre":"AMETHYST","categoria":"Hombre","descripcion":"Tropical, rosas, oud, cítrico","precio":80000,"imagen":"imagenes/hombre/amethyst.jpg"},
    {"codigo":"MEL-H073","nombre":"AMETHYST ","categoria":"Hombre","descripcion":"Tropical, rosas, oud, cítrico","precio":100000,"imagen":"imagenes/hombre/amethyst-20.jpg"},
    {"codigo":"MEL-H074","nombre":"SUBLIME","categoria":"Hombre","descripcion":"Afrutado, fresco, tropical","precio":80000,"imagen":"imagenes/hombre/sublime.jpg"},
    {"codigo":"MEL-H075","nombre":"SUBLIME ","categoria":"Hombre","descripcion":"Afrutado, fresco, tropical","precio":100000,"imagen":"imagenes/hombre/sublime-20.jpg"},
    {"codigo":"MEL-H076","nombre":"AJWAD","categoria":"Hombre","descripcion":"Afrutados, cuero, tropical","precio":80000,"imagen":"imagenes/hombre/ajwad.jpg"},
    {"codigo":"MEL-H077","nombre":"EMEER","categoria":"Hombre","descripcion":"Aromatico, Amaderado, citrico","precio":80000,"imagen":"imagenes/hombre/emeer.jpg"},
    {"codigo":"MEL-H078","nombre":"SHAHEEN GOLD","categoria":"Hombre","descripcion":"Dulce, especiado, oriental","precio":80000,"imagen":"imagenes/hombre/shaheen-gold.jpg"},
    {"codigo":"MEL-H079","nombre":"ART OF UNIVERSE","categoria":"Hombre","descripcion":"Fresca, dulce, elegante","precio":80000,"imagen":"imagenes/hombre/art-of-universe.jpg"},
    {"codigo":"MEL-H080","nombre":"HIS CONFESSION","categoria":"Hombre","descripcion":"Amaderada, dulce, intensa","precio":80000,"imagen":"imagenes/hombre/his-confession.jpg"},
    {"codigo":"MEL-H081","nombre":"KHAMRAH","categoria":"Hombre","descripcion":"Dulce, canela, ámbar","precio":80000,"imagen":"imagenes/hombre/khamrah.jpg"},
    {"codigo":"MEL-H082","nombre":"KHAMRAH QAHWA","categoria":"Hombre","descripcion":"Dulce, avainillado, ámbar","precio":80000,"imagen":"imagenes/hombre/khamrah-qahwa.jpg"},
    {"codigo":"MEL-H083","nombre":"KHAMRAH WAHA","categoria":"Hombre","descripcion":"Tropical, fresca, avainillada","precio":80000,"imagen":"imagenes/hombre/khamrah-waha.jpg"},
    {"codigo":"MEL-H084","nombre":"KHAMRAH DUKHAN","categoria":"Hombre","descripcion":"Dulce, especiado, seductor","precio":80000,"imagen":"imagenes/hombre/khamrah-dukhan.jpg"},
    {"codigo":"MEL-H085","nombre":"KHAMRAH LUJO ","categoria":"Hombre","descripcion":"Dulce, canela, ámbar","precio":100000,"imagen":"imagenes/hombre/khamrah-lujo-20.jpg"},
    {"codigo":"MEL-H086","nombre":"QAHWA LUJO ","categoria":"Hombre","descripcion":"Dulce, avainillado, ámbar","precio":100000,"imagen":"imagenes/hombre/qahwa-lujo-20.jpg"},
    {"codigo":"MEL-H087","nombre":"DUKHAN LUJO ","categoria":"Hombre","descripcion":"Dulce, especiado, seductor","precio":100000,"imagen":"imagenes/hombre/dukhan-lujo-20.jpg"},
    {"codigo":"MEL-H088","nombre":"ORIENTICA AMBER ROUGE ","categoria":"Hombre","descripcion":"Ámbar, amaderado, cálido","precio":95000,"imagen":"imagenes/hombre/orientica-amber-rouge.jpg"},
    {"codigo":"MEL-H089","nombre":"SAFRON ","categoria":"Hombre","descripcion":"Cálido especiado, amaderado, ambar","precio":90000,"imagen":"imagenes/hombre/safron.jpg"},
    {"codigo":"MEL-H090","nombre":"VELVET GOLD ","categoria":"Hombre","descripcion":"Atalcado, almizcado, pachuli","precio":90000,"imagen":"imagenes/hombre/velvet-gold.jpg"},
    {"codigo":"MEL-H091","nombre":"INITIO","categoria":"Hombre","descripcion":"Calido especiado, Fresco especiado, oud","precio":80000,"imagen":"imagenes/hombre/initio.jpg"},
    {"codigo":"MEL-H092","nombre":"ORIENTICA EXCLUSIVE ROYAL AMBER ","categoria":"Hombre","descripcion":"Afrutado, dulce, ambarado","precio":95000,"imagen":"imagenes/hombre/orientica-royal-amber.jpg"},
    {"codigo":"MEL-H093","nombre":"ORIENTICA AZURE FANTASY ","categoria":"Hombre","descripcion":"Fresco, cítrico, elegante","precio":95000,"imagen":"imagenes/hombre/orientica-azure.jpg"},
    {"codigo":"MEL-H094","nombre":"ARABIANS TONKA","categoria":"Hombre","descripcion":"Dulce, avainillado, ámbar","precio":80000,"imagen":"imagenes/hombre/arabians-tonka.jpg"},
    {"codigo":"MEL-H095","nombre":"ARABIANS","categoria":"Hombre","descripcion":"Aromatico, calido especiado, oud","precio":80000,"imagen":"imagenes/hombre/arabians.jpg"},
    {"codigo":"MEL-H096","nombre":"STARRY NIGHT","categoria":"Hombre","descripcion":"Atalcado, citrico, almizcado","precio":80000,"imagen":"imagenes/hombre/starry-night.jpg"},
    {"codigo":"MEL-H097","nombre":"AHLI VEGA","categoria":"Hombre","descripcion":"Afrutado, amaderado, atalcado","precio":80000,"imagen":"imagenes/hombre/ahli-vega.jpg"},
    {"codigo":"MEL-H098","nombre":"AHLI KARPOS","categoria":"Hombre","descripcion":"Mango, cítrico, ámbar","precio":80000,"imagen":"imagenes/hombre/ahli-karpos.jpg"},
    {"codigo":"MEL-H099","nombre":"MANDARIN SKY","categoria":"Hombre","descripcion":"Cítrico, dulce, caramelo","precio":80000,"imagen":"imagenes/hombre/mandarin-sky.jpg"},
    {"codigo":"MEL-H100","nombre":"AHLI CORVUS","categoria":"Hombre","descripcion":"Afrutado, vainilla, floral","precio":80000,"imagen":"imagenes/hombre/ahli-corvus.jpg"},
    {"codigo":"MEL-H101","nombre":"ODYSSEY SPECTRA","categoria":"Hombre","descripcion":"Cálido especiado, dulce, avainillado","precio":80000,"imagen":"imagenes/hombre/odyssey-spectra.jpg"},
    {"codigo":"MEL-H102","nombre":"ODISSEY CHOCOLATE","categoria":"Hombre","descripcion":"Chocolate, dulce, cremoso","precio":80000,"imagen":"imagenes/hombre/odyssey-chocolate.jpg"},
    {"codigo":"MEL-H103","nombre":"MANDARIN ELIXIR","categoria":"Hombre","descripcion":"Avainillado, cítrico, dulce","precio":80000,"imagen":"imagenes/hombre/mandarin-elixir.jpg"},
    {"codigo":"MEL-H104","nombre":"ODISSEY LIMONI","categoria":"Hombre","descripcion":"Fresco, citrico, vibrante","precio":80000,"imagen":"imagenes/hombre/odyssey-limoni.jpg"},
    {"codigo":"MEL-H105","nombre":"OMBRE NOMADE","categoria":"Hombre","descripcion":"Ambar, oud, Cuero","precio":80000,"imagen":"imagenes/hombre/ombre-nomade.jpg"},
    {"codigo":"MEL-H106","nombre":"CLUB DE NUIT BESTIA NEGRA","categoria":"Hombre","descripcion":"Citrico, Afrutado, Cuero","precio":80000,"imagen":"imagenes/hombre/club-de-nuit-bestia.jpg"},
    {"codigo":"MEL-H107","nombre":"CLUB DE NUIT UNTOLD","categoria":"Hombre","descripcion":"Especiado, Amaderado, sofisticado","precio":80000,"imagen":"imagenes/hombre/club-de-nuit-untold.jpg"},
    {"codigo":"MEL-H108","nombre":"HARAMAIN AMBER OUD","categoria":"Hombre","descripcion":"dulce, afrutado, ambar","precio":80000,"imagen":"imagenes/hombre/haramain-amber-oud.jpg"},
    {"codigo":"MEL-H109","nombre":"VALENTINO BOR IN ROMA","categoria":"Hombre","descripcion":"Amaderado, mineral, aromatico","precio":80000,"imagen":"imagenes/hombre/valentino-bor.jpg"},
    {"codigo":"MEL-H110","nombre":"TOMMY","categoria":"Hombre","descripcion":"Verde, Fresco especiado, Citrico","precio":80000,"imagen":"imagenes/hombre/tommy.jpg"},
    {"codigo":"MEL-H111","nombre":"SWIS ARMY","categoria":"Hombre","descripcion":"Aromatico, fresco, verde","precio":80000,"imagen":"imagenes/hombre/swis-army.jpg"},
    {"codigo":"MEL-H112","nombre":"NAUTICA","categoria":"Hombre","descripcion":"Aromático, fresco, verde","precio":80000,"imagen":"imagenes/hombre/nautica.jpg"},
    {"codigo":"MEL-H113","nombre":"BACCARAT ROUGE","categoria":"Hombre","descripcion":"Amaderado, almendrado, ámbar","precio":80000,"imagen":"imagenes/hombre/baccarat-rouge.jpg"},
    {"codigo":"MEL-H114","nombre":"STRNGER WITH YOU","categoria":"Hombre","descripcion":"Cítrico, avainillado, cálido","precio":80000,"imagen":"imagenes/hombre/stranger-with-you.jpg"},
    {"codigo":"MEL-H115","nombre":"ISSEY MIYAKE","categoria":"Hombre","descripcion":"Cítrico, afrutado, ácido","precio":80000,"imagen":"imagenes/hombre/issey-miyake.jpg"},
    {"codigo":"MEL-H116","nombre":"SANTAL 33","categoria":"Hombre","descripcion":"Amaderado, atalcado, cuero","precio":80000,"imagen":"imagenes/hombre/santal-33.jpg"},
    {"codigo":"MEL-H117","nombre":"AGUA DI GIOI","categoria":"Hombre","descripcion":"Aromático, cítrico, floral","precio":80000,"imagen":"imagenes/hombre/agua-di-gioi.jpg"},
    {"codigo":"MEL-H118","nombre":"AGUA DI GIO PROFUNDO","categoria":"Hombre","descripcion":"Aromático, fresco, marino","precio":80000,"imagen":"imagenes/hombre/agua-di-gio-profundo.jpg"},
    {"codigo":"MEL-H119","nombre":"CK ONE","categoria":"Hombre","descripcion":"Cítrico, verde, amaderado","precio":80000,"imagen":"imagenes/hombre/ck-one.jpg"},
    {"codigo":"MEL-H120","nombre":"9 PM","categoria":"Hombre","descripcion":"Vainilla, ámbar, aromático","precio":80000,"imagen":"imagenes/hombre/9pm.jpg"},
    {"codigo":"MEL-H121","nombre":"9 AM","categoria":"Hombre","descripcion":"Fresco, Citrico, Juvenil","precio":80000,"imagen":"imagenes/hombre/9am.jpg"},
    {"codigo":"MEL-H122","nombre":"9 PM REBEL","categoria":"Hombre","descripcion":"Dulce, especiado, nocturno","precio":80000,"imagen":"imagenes/hombre/9pm-rebel.jpg"},
    {"codigo":"MEL-H123","nombre":"9 PM ELIXIR","categoria":"Hombre","descripcion":"Cuero, avainillado, especiado","precio":80000,"imagen":"imagenes/hombre/9pm-elixir.jpg"},
    {"codigo":"MEL-H124","nombre":"SPICEBOMB","categoria":"Hombre","descripcion":"Cálido especiado, canela, tabaco","precio":80000,"imagen":"imagenes/hombre/spicebomb.jpg"},
    {"codigo":"MEL-H125","nombre":"BVLGARI MAN BLACK","categoria":"Hombre","descripcion":"Calido especiado, amaderado, cuero","precio":80000,"imagen":"imagenes/hombre/bvlgari-man-black.jpg"},
    {"codigo":"MEL-H126","nombre":"POLO BLUE","categoria":"Hombre","descripcion":"Aromatico, marino, amaderado","precio":80000,"imagen":"imagenes/hombre/polo-blue.jpg"},
    {"codigo":"MEL-H127","nombre":"POLO RED","categoria":"Hombre","descripcion":"Citrico, afrutado, ambar","precio":80000,"imagen":"imagenes/hombre/polo-red.jpg"},
    {"codigo":"MEL-M001","nombre":"212 SEXY","categoria":"Mujer","descripcion":"Dulce, especiado, caramelo","precio":80000,"imagen":"imagenes/mujer/212-sexy.jpg"},
    {"codigo":"MEL-M002","nombre":"212 ROSE","categoria":"Mujer","descripcion":"Frutado, floral, amaderado","precio":80000,"imagen":"imagenes/mujer/212-rose.jpg"},
    {"codigo":"MEL-M003","nombre":"GOOD GIRL BLUSH","categoria":"Mujer","descripcion":"Floral, avainillado, cítrico","precio":80000,"imagen":"imagenes/mujer/good-girl-blush.jpg"},
    {"codigo":"MEL-M004","nombre":"212 PATINETA","categoria":"Mujer","descripcion":"Afrutado, floral blanco, dulce","precio":80000,"imagen":"imagenes/mujer/212-patineta.jpg"},
    {"codigo":"MEL-M005","nombre":"CH DAMA","categoria":"Mujer","descripcion":"Cítrico, amaderado, cuero","precio":80000,"imagen":"imagenes/mujer/ch-dama.jpg"},
    {"codigo":"MEL-M006","nombre":"LA BOMBA","categoria":"Mujer","descripcion":"Floral, afrutado, ambarado","precio":90000,"imagen":"imagenes/mujer/la-bomba.jpg"},
    {"codigo":"MEL-M007","nombre":"GOOD GIRL SUPREME","categoria":"Mujer","descripcion":"Floral blanco, avainillado, afrutado","precio":80000,"imagen":"imagenes/mujer/good-girl-supreme.jpg"},
    {"codigo":"MEL-M008","nombre":"VERY GOOD","categoria":"Mujer","descripcion":"Afrutado, Rosas, Fresco","precio":80000,"imagen":"imagenes/mujer/very-good.jpg"},
    {"codigo":"MEL-M009","nombre":"GOOD GIRL","categoria":"Mujer","descripcion":"Dulce, Floral blanco, Calido especiado","precio":80000,"imagen":"imagenes/mujer/good-girl.jpg"},
    {"codigo":"MEL-M010","nombre":"TOY2","categoria":"Mujer","descripcion":"Afrutados, Florales, fresco","precio":80000,"imagen":"imagenes/mujer/toy2.jpg"},
    {"codigo":"MEL-M011","nombre":"BUBBLE GUM","categoria":"Mujer","descripcion":"Afrutados, dulce, rosas","precio":80000,"imagen":"imagenes/mujer/bubble-gum.jpg"},
    {"codigo":"MEL-M012","nombre":"TOY PEARL","categoria":"Mujer","descripcion":"Aromático, cítrico, amaderado","precio":80000,"imagen":"imagenes/mujer/toy-pearl.jpg"},
    {"codigo":"MEL-M013","nombre":"PURE XS","categoria":"Mujer","descripcion":"Avainillado, dulce, amaderado","precio":80000,"imagen":"imagenes/mujer/pure-xs.jpg"},
    {"codigo":"MEL-M014","nombre":"FAME","categoria":"Mujer","descripcion":"Tropical, avainillado, afrutado","precio":80000,"imagen":"imagenes/mujer/fame.jpg"},
    {"codigo":"MEL-M015","nombre":"BURBERRY HER","categoria":"Mujer","descripcion":"Vainilla, Dulce, Floral","precio":80000,"imagen":"imagenes/mujer/burberry-her.jpg"},
    {"codigo":"MEL-M016","nombre":"OLYMPEA","categoria":"Mujer","descripcion":"Avainillado, amaderado, atalcado","precio":80000,"imagen":"imagenes/mujer/olympea.jpg"},
    {"codigo":"MEL-M017","nombre":"ELEGANT","categoria":"Mujer","descripcion":"Fresco, atalcado, verde","precio":80000,"imagen":"imagenes/mujer/elegant.jpg"},
    {"codigo":"MEL-M018","nombre":"SPARKING","categoria":"Mujer","descripcion":"Dulce, caramelo","precio":80000,"imagen":"imagenes/mujer/sparking.jpg"},
    {"codigo":"MEL-M019","nombre":"NATURAL","categoria":"Mujer","descripcion":"Dulce, afrutados, coco","precio":80000,"imagen":"imagenes/mujer/natural.jpg"},
    {"codigo":"MEL-M020","nombre":"OMNIA AMETHYSTE","categoria":"Mujer","descripcion":"Atalcado, iris, avainillado","precio":80000,"imagen":"imagenes/mujer/omnia-amethyste.jpg"},
    {"codigo":"MEL-M021","nombre":"OMNIA CORAL","categoria":"Mujer","descripcion":"Florales, amaderado, fresco especiado","precio":80000,"imagen":"imagenes/mujer/omnia-coral.jpg"},
    {"codigo":"MEL-M022","nombre":"OMNIA CRISTAL","categoria":"Mujer","descripcion":"Florales, amaderado, fresco especiado","precio":80000,"imagen":"imagenes/mujer/omnia-cristal.jpg"},
    {"codigo":"MEL-M023","nombre":"MAYAR ","categoria":"Mujer","descripcion":"Frutal, floral, dulce","precio":95000,"imagen":"imagenes/mujer/mayar.jpg"},
    {"codigo":"MEL-M024","nombre":"ECLAIRE ","categoria":"Mujer","descripcion":"Dulce, vainilla, floral","precio":95000,"imagen":"imagenes/mujer/eclaire.jpg"},
    {"codigo":"MEL-M025","nombre":"SCANDAL","categoria":"Mujer","descripcion":"Amielado, dulce, floral blanco","precio":80000,"imagen":"imagenes/mujer/scandal.jpg"},
    {"codigo":"MEL-M026","nombre":"CLASIQUE","categoria":"Mujer","descripcion":"Dulce, floral, blanco, atalcado","precio":80000,"imagen":"imagenes/mujer/clasique.jpg"},
    {"codigo":"MEL-M027","nombre":"LA BELLE","categoria":"Mujer","descripcion":"Avainillado, dulce, ámbar","precio":80000,"imagen":"imagenes/mujer/la-belle.jpg"},
    {"codigo":"MEL-M028","nombre":"YUM YUM LUJO ","categoria":"Mujer","descripcion":"Afrutado, avainillado, atalcado","precio":100000,"imagen":"imagenes/mujer/yum-yum-lujo.jpg"},
    {"codigo":"MEL-M029","nombre":"YUM YUM ","categoria":"Mujer","descripcion":"Afrutado, avainillado, atalcado","precio":90000,"imagen":"imagenes/mujer/yum-yum.jpg"},
    {"codigo":"MEL-M030","nombre":"ODISSEY CANDEE","categoria":"Mujer","descripcion":"Florales, afrutados, cítrico","precio":80000,"imagen":"imagenes/mujer/odyssey-candee.jpg"},
    {"codigo":"MEL-M031","nombre":"ISLAND BLISS ","categoria":"Mujer","descripcion":"Avainillado, dulce, coco","precio":90000,"imagen":"imagenes/mujer/island-bliss.jpg"},
    {"codigo":"MEL-M032","nombre":"CLUB DE NUIT UNTOLD","categoria":"Mujer","descripcion":"Especiado, amaderado, sofisticado","precio":80000,"imagen":"imagenes/mujer/club-de-nuit-untold.jpg"},
    {"codigo":"MEL-M033","nombre":"ODISSEY LIMONI","categoria":"Mujer","descripcion":"Fresco, cítrico, vibrante","precio":80000,"imagen":"imagenes/mujer/odyssey-limoni.jpg"},
    {"codigo":"MEL-M034","nombre":"BHARARA ROSE ","categoria":"Mujer","descripcion":"Frutal, floral, dulce","precio":100000,"imagen":"imagenes/mujer/bharara-rose.jpg"},
    {"codigo":"MEL-M035","nombre":"BHARARA KING ","categoria":"Mujer","descripcion":"Dulce, fresco, ambarado","precio":100000,"imagen":"imagenes/mujer/bharara-king.jpg"},
    {"codigo":"MEL-M036","nombre":"HAYA ","categoria":"Mujer","descripcion":"Floral, dulce, envolvente","precio":110000,"imagen":"imagenes/mujer/haya.jpg"},
    {"codigo":"MEL-M037","nombre":"BHARARA NICHE FEMME ","categoria":"Mujer","descripcion":"Elegante, femenina, floral","precio":95000,"imagen":"imagenes/mujer/bharara-niche.jpg"},
    {"codigo":"MEL-M038","nombre":"BRIGHT CRYSTAL","categoria":"Mujer","descripcion":"Floral, afrutado, fresco","precio":80000,"imagen":"imagenes/mujer/bright-crystal.jpg"},
    {"codigo":"MEL-M039","nombre":"360","categoria":"Mujer","descripcion":"Floral blanco, florales, fresco","precio":80000,"imagen":"imagenes/mujer/360.jpg"},
    {"codigo":"MEL-M040","nombre":"THANK YOU NEXT","categoria":"Mujer","descripcion":"Dulce, coco, afrutados","precio":80000,"imagen":"imagenes/mujer/thank-you-next.jpg"},
    {"codigo":"MEL-M041","nombre":"CANDY","categoria":"Mujer","descripcion":"Dulce, avainillado, afrutado","precio":80000,"imagen":"imagenes/mujer/candy.jpg"},
    {"codigo":"MEL-M042","nombre":"THANK YOU NEXT 2.0","categoria":"Mujer","descripcion":"Dulce, amaderado, afrutados","precio":80000,"imagen":"imagenes/mujer/thank-you-next-2.jpg"},
    {"codigo":"MEL-M043","nombre":"CLOUD","categoria":"Mujer","descripcion":"Dulce, lactónico, avainilaldo","precio":80000,"imagen":"imagenes/mujer/cloud.jpg"},
    {"codigo":"MEL-M044","nombre":"LIGHT BLUE","categoria":"Mujer","descripcion":"Cítrico, amaderado, fresco","precio":80000,"imagen":"imagenes/mujer/light-blue.jpg"},
    {"codigo":"MEL-M045","nombre":"ISLAM BLISS ","categoria":"Mujer","descripcion":"Vainilla, dulce, gourmand","precio":100000,"imagen":"imagenes/mujer/islam-bliss.jpg"},
    {"codigo":"MEL-M046","nombre":"NOBLE BLUSH ","categoria":"Mujer","descripcion":"Dulce, cremoso, Floral","precio":95000,"imagen":"imagenes/mujer/noble-blush.jpg"},
    {"codigo":"MEL-M047","nombre":"MEOW","categoria":"Mujer","descripcion":"Avainillado, Floral blanco, dulce","precio":80000,"imagen":"imagenes/mujer/meow.jpg"},
    {"codigo":"MEL-M048","nombre":"VIDA BELLA","categoria":"Mujer","descripcion":"Dulce, Avainillado, Afrutado","precio":80000,"imagen":"imagenes/mujer/vida-bella.jpg"},
    {"codigo":"MEL-M049","nombre":"VALENTINO DONNA","categoria":"Mujer","descripcion":"Amaderado, avainillado, floral blanco","precio":80000,"imagen":"imagenes/mujer/valentino-donna.jpg"},
    {"codigo":"MEL-M050","nombre":"BACCARAT ROUGE","categoria":"Mujer","descripcion":"Ámbar, almendrado, amaderado","precio":80000,"imagen":"imagenes/mujer/baccarat-rouge.jpg"},
    {"codigo":"MEL-M051","nombre":"RALPH","categoria":"Mujer","descripcion":"Florales, afrutados, cítrico","precio":80000,"imagen":"imagenes/mujer/ralph.jpg"},
    {"codigo":"MEL-M052","nombre":"DELINA","categoria":"Mujer","descripcion":"Rosas, afrutados, avainillados","precio":80000,"imagen":"imagenes/mujer/delina.jpg"},
    {"codigo":"MEL-M053","nombre":"PRADA MILANO","categoria":"Mujer","descripcion":"Dulce, Floral, Sofisticado","precio":80000,"imagen":"imagenes/mujer/prada-milano.jpg"},
    {"codigo":"MEL-M054","nombre":"YARA TOUCH","categoria":"Mujer","descripcion":"Tropical, dulce, avainillado","precio":80000,"imagen":"imagenes/mujer/yara-touch.jpg"},
    {"codigo":"MEL-M055","nombre":"AJWAD","categoria":"Mujer","descripcion":"Afrutado, dulce, avainillado","precio":80000,"imagen":"imagenes/mujer/ajwad.jpg"},
    {"codigo":"MEL-M056","nombre":"YARA CANDY","categoria":"Mujer","descripcion":"Avainillado, afrutados, floral blanco","precio":80000,"imagen":"imagenes/mujer/yara-candy.jpg"},
    {"codigo":"MEL-M057","nombre":"YARA MOI","categoria":"Mujer","descripcion":"Amaderado, caramelo, floral blanco","precio":80000,"imagen":"imagenes/mujer/yara-moi.jpg"},
    {"codigo":"MEL-M058","nombre":"YARA ELIXIR","categoria":"Mujer","descripcion":"Dulce, Floral, Sensual","precio":80000,"imagen":"imagenes/mujer/yara-elixir.jpg"},
    {"codigo":"MEL-M059","nombre":"YARA","categoria":"Mujer","descripcion":"Dulce, Avainillado, atalcado","precio":80000,"imagen":"imagenes/mujer/yara.jpg"},
    {"codigo":"MEL-M060","nombre":"HER CONFESSION","categoria":"Mujer","descripcion":"Dulce, suave, cremosa","precio":80000,"imagen":"imagenes/mujer/her-confession.jpg"},
    {"codigo":"MEL-M061","nombre":"ART OF UNIVERSE","categoria":"Mujer","descripcion":"Fresca, dulce, elegante","precio":80000,"imagen":"imagenes/mujer/art-of-universe.jpg"},
    {"codigo":"MEL-M062","nombre":"SHAHEEN GOLD","categoria":"Mujer","descripcion":"Dulce, especiado, oriental","precio":80000,"imagen":"imagenes/mujer/shaheen-gold.jpg"},
    {"codigo":"MEL-M063","nombre":"KHAMRAH","categoria":"Mujer","descripcion":"Dulce, ámbar, canela","precio":80000,"imagen":"imagenes/mujer/khamrah.jpg"},
    {"codigo":"MEL-M064","nombre":"KHAMRAH QAHWA","categoria":"Mujer","descripcion":"Cálido especiado, dulce, avainillado","precio":80000,"imagen":"imagenes/mujer/khamrah-qahwa.jpg"},
    {"codigo":"MEL-M065","nombre":"KHAMRAH DUKHAN","categoria":"Mujer","descripcion":"Dulce, especiado, Seductor","precio":80000,"imagen":"imagenes/mujer/khamrah-dukhan.jpg"},
    {"codigo":"MEL-M066","nombre":"KHAMRAH WAHA","categoria":"Mujer","descripcion":"Tropical, fresca, avainillada","precio":80000,"imagen":"imagenes/mujer/khamrah-waha.jpg"},
    {"codigo":"MEL-M067","nombre":"KHAMRAH LUJO ","categoria":"Mujer","descripcion":"Dulce, canela, ámbar","precio":100000,"imagen":"imagenes/mujer/khamrah-lujo.jpg"},
    {"codigo":"MEL-M068","nombre":"QAHWA LUJO ","categoria":"Mujer","descripcion":"Calido especiado, dulce, avainillado","precio":100000,"imagen":"imagenes/mujer/qahwa-lujo.jpg"},
    {"codigo":"MEL-M069","nombre":"DUKHAN LUJO ","categoria":"Mujer","descripcion":"Dulce, especiado, seductor","precio":100000,"imagen":"imagenes/mujer/dukhan-lujo.jpg"},
    {"codigo":"MEL-M070","nombre":"SUBLIME","categoria":"Mujer","descripcion":"Afrutado, fresco, Tropical","precio":80000,"imagen":"imagenes/mujer/sublime.jpg"},
    {"codigo":"MEL-M071","nombre":"SUBLIME ","categoria":"Mujer","descripcion":"Afrutado, fresco, Tropical","precio":100000,"imagen":"imagenes/mujer/sublime-20.jpg"},
    {"codigo":"MEL-M072","nombre":"OUD FOR GLORY","categoria":"Mujer","descripcion":"Oud, Calido especiado, fresco especiado","precio":80000,"imagen":"imagenes/mujer/oud-for-glory.jpg"},
    {"codigo":"MEL-M073","nombre":"OUD FOR GLORY ","categoria":"Mujer","descripcion":"Oud, Calido especiado, fresco especiado","precio":100000,"imagen":"imagenes/mujer/oud-for-glory-20.jpg"},
    {"codigo":"MEL-M074","nombre":"AMETHYST","categoria":"Mujer","descripcion":"Rosas, Oud, Ambar","precio":80000,"imagen":"imagenes/mujer/amethyst.jpg"},
    {"codigo":"MEL-M075","nombre":"AMETHYST ","categoria":"Mujer","descripcion":"Rosas, Oud, Ambar","precio":100000,"imagen":"imagenes/mujer/amethyst-20.jpg"},
    {"codigo":"MEL-M076","nombre":"HONOR Y GLORY","categoria":"Mujer","descripcion":"Dulce, cálido, avainillado","precio":80000,"imagen":"imagenes/mujer/honor-y-glory.jpg"},
    {"codigo":"MEL-M077","nombre":"HONOR Y GLORY ","categoria":"Mujer","descripcion":"Dulce, cálido, avainillado","precio":100000,"imagen":"imagenes/mujer/honor-y-glory-20.jpg"},
    {"codigo":"MEL-M078","nombre":"HARAMAIN AMBER OUD","categoria":"Mujer","descripcion":"Dulce, afrutado, ambar","precio":80000,"imagen":"imagenes/mujer/haramain-amber-oud.jpg"},
    {"codigo":"MEL-M079","nombre":"AMBER OUD ULTRA VIOLET LUJO ","categoria":"Mujer","descripcion":"Rosas, Jazmin, Fresca","precio":100000,"imagen":"imagenes/mujer/amber-oud-ultra.jpg"},
    {"codigo":"MEL-M080","nombre":"ODISSEY CHOCOLATE","categoria":"Mujer","descripcion":"Chocolate, dulce, cremoso","precio":80000,"imagen":"imagenes/mujer/odyssey-chocolate.jpg"},
    {"codigo":"MEL-M081","nombre":"ARABIANS","categoria":"Mujer","descripcion":"Aromático, cálido especiado, oud","precio":80000,"imagen":"imagenes/mujer/arabians.jpg"},
    {"codigo":"MEL-M082","nombre":"ARABIANS TONKA","categoria":"Mujer","descripcion":"Dulce, avainillado, ámbar","precio":80000,"imagen":"imagenes/mujer/arabians-tonka.jpg"},
    {"codigo":"MEL-M083","nombre":"STARRY NIGHT","categoria":"Mujer","descripcion":"Atalcado, cítrico, almizcado","precio":80000,"imagen":"imagenes/mujer/starry-night.jpg"},
    {"codigo":"MEL-M084","nombre":"ORIENTICA AMBER ROUGE ","categoria":"Mujer","descripcion":"Ámbar, amaderado, cálido especiado","precio":95000,"imagen":"imagenes/mujer/orientica-amber-rouge.jpg"},
    {"codigo":"MEL-M085","nombre":"ORIENTICA EXCLUSIVE ROYAL AMBER","categoria":"Mujer","descripcion":"Afrutado, Dulce, Ambarado","precio":95000,"imagen":"imagenes/mujer/orientica-royal-amber.jpg"},
    {"codigo":"MEL-M086","nombre":"ORIENTICA AZURE FANTASY ","categoria":"Mujer","descripcion":"Fresco, Citrico, elegante","precio":95000,"imagen":"imagenes/mujer/orientica-azure.jpg"},
    {"codigo":"MEL-M087","nombre":"SAFRON ","categoria":"Mujer","descripcion":"Calido especiado, Amaderado, Ambar","precio":90000,"imagen":"imagenes/mujer/safron.jpg"},
    {"codigo":"MEL-M088","nombre":"VELVET GOLD ","categoria":"Mujer","descripcion":"Atalcado, almizcado, pachuli","precio":90000,"imagen":"imagenes/mujer/velvet-gold.jpg"},
    {"codigo":"MEL-M089","nombre":"ESCADA","categoria":"Mujer","descripcion":"Floral, fresco, dulce","precio":80000,"imagen":"imagenes/mujer/escada.jpg"},
    {"codigo":"MEL-M090","nombre":"MISS DIOR","categoria":"Mujer","descripcion":"Avainillado, atalcado","precio":80000,"imagen":"imagenes/mujer/miss-dior.jpg"},
    {"codigo":"MEL-M091","nombre":"FANTASY BRITNEY","categoria":"Mujer","descripcion":"Dulce, afrutado, tropical","precio":80000,"imagen":"imagenes/mujer/fantasy-britney.jpg"},
    {"codigo":"MEL-M092","nombre":"PARIS HILTON","categoria":"Mujer","descripcion":"Afrutado, Floral Blanco, Fresco","precio":80000,"imagen":"imagenes/mujer/paris-hilton.jpg"},
    {"codigo":"MEL-M093","nombre":"AHLI KARPOS","categoria":"Mujer","descripcion":"Frutal, Tropical, Dulce","precio":80000,"imagen":"imagenes/mujer/ahli-karpos.jpg"},
    {"codigo":"MEL-M094","nombre":"AHLI VEGA","categoria":"Mujer","descripcion":"Afrutado, Amaderado, Rosas","precio":80000,"imagen":"imagenes/mujer/ahli-vega.jpg"},
    {"codigo":"MEL-M095","nombre":"AHLI CORVUS","categoria":"Mujer","descripcion":"Ambar, Frutal, Vainilla","precio":80000,"imagen":"imagenes/mujer/ahli-corvus.jpg"},
    {"codigo":"MEL-M096","nombre":"INITIO","categoria":"Mujer","descripcion":"Cálido, especiado, oud","precio":80000,"imagen":"imagenes/mujer/initio.jpg"},
    {"codigo":"MEL-M097","nombre":"BLACK PHANTOM","categoria":"Mujer","descripcion":"Caramelo, café, amaderado","precio":80000,"imagen":"imagenes/mujer/black-phantom.jpg"},
    {"codigo":"MEL-M098","nombre":"COCO CHANEL","categoria":"Mujer","descripcion":"Citrico, Amaderado, Floral","precio":80000,"imagen":"imagenes/mujer/coco-chanel.jpg"},
    {"codigo":"MEL-M099","nombre":"CAN CAN","categoria":"Mujer","descripcion":"Fresco, Floral, Vainilla","precio":80000,"imagen":"imagenes/mujer/can-can.jpg"},
    {"codigo":"MEL-M100","nombre":"CHANEL #5","categoria":"Mujer","descripcion":"Floral, vainilla, cítrico","precio":80000,"imagen":"imagenes/mujer/chanel-5.jpg"},
    {"codigo":"MEL-M101","nombre":"CHANCE CHANEL","categoria":"Mujer","descripcion":"Floral, Afrutada, Limon","precio":80000,"imagen":"imagenes/mujer/chance-chanel.jpg"},
    {"codigo":"MEL-L001","nombre":"BHARARA KING","categoria":"Lujo","descripcion":"Cítrico, afrutado, vainilla, almizcle, ámbar","precio":100000,"imagen":"imagenes/lujo/bharara-king.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L002","nombre":"BHARARA ROSE","categoria":"Lujo","descripcion":"Rosa turca, frutos rojos, almizcle blanco, ámbar","precio":100000,"imagen":"imagenes/lujo/bharara-rose.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L003","nombre":"BHARARA NICHE FEMME","categoria":"Lujo","descripcion":"Cítricos brillantes, flores blancas, almizcle suave","precio":100000,"imagen":"imagenes/lujo/bharara-niche.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L004","nombre":"BHARARA SCARLET","categoria":"Lujo","descripcion":"Frutal dulce, rosa, vainilla, ámbar","precio":100000,"imagen":"imagenes/lujo/bharara-scarlet.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L005","nombre":"ERBA PURA XERJOFF","categoria":"Lujo","descripcion":"Cítricos mediterráneos, frutas dulces, almizcle blanco, ámbar","precio":100000,"imagen":"imagenes/lujo/erba-pura-xerjoff.jpg","etiqueta":"Premium"},
    {"codigo":"MEL-L006","nombre":"AFEEF LATTAFA","categoria":"Lujo","descripcion":"Especias árabes, oud, ámbar, dulzor balsámico","precio":100000,"imagen":"imagenes/lujo/afeef-lattafa.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L007","nombre":"OUD FOR GLORY","categoria":"Lujo","descripcion":"Oud intenso, especias cálidas, pachulí, ámbar","precio":100000,"imagen":"imagenes/lujo/oud-for-glory.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L008","nombre":"HONOR Y GLORY","categoria":"Lujo","descripcion":"Oud fresco, especiado, madera seca","precio":100000,"imagen":"imagenes/lujo/honor-y-glory.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L009","nombre":"SUBLIME","categoria":"Lujo","descripcion":"Frutas tropicales, flores frescas, almizcle ligero","precio":100000,"imagen":"imagenes/lujo/sublime.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L010","nombre":"AMETHYST","categoria":"Lujo","descripcion":"Rosa, frutos rojos, violeta, almizcle","precio":100000,"imagen":"imagenes/lujo/amethyst.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L011","nombre":"NOBLE BLUSH","categoria":"Lujo","descripcion":"Vainilla gourmand, caramelo, flores dulces","precio":100000,"imagen":"imagenes/lujo/noble-blush.jpg","etiqueta":"Exclusivo"},
    {"codigo":"MEL-L012","nombre":"FAKHAR BLACK","categoria":"Lujo","descripcion":"Cítricos, especias, lavanda, ámbar, pachulí","precio":100000,"imagen":"imagenes/lujo/fakhar-black.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L013","nombre":"9 PM NIGHT OUT","categoria":"Lujo","descripcion":"Manzana, canela, lavanda, bergamota, vainilla, tonka, ámbar","precio":100000,"imagen":"imagenes/lujo/9pm-night.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L014","nombre":"KHAMRAH","categoria":"Lujo","descripcion":"Canela, nuez moscada, dátiles, praliné, vainilla, tonka, ámbar","precio":100000,"imagen":"imagenes/lujo/khamrah.jpg","etiqueta":"Popular"},
    {"codigo":"MEL-L015","nombre":"KHAMRAH QAHWA","categoria":"Lujo","descripcion":"Café especiado, vainilla, ámbar, dulzor gourmand","precio":100000,"imagen":"imagenes/lujo/khamrah-qahwa.jpg","etiqueta":"Popular"},
    {"codigo":"MEL-L016","nombre":"KHAMRAH DUKHAN","categoria":"Lujo","descripcion":"Especias ahumadas, oud, vainilla, ámbar","precio":100000,"imagen":"imagenes/lujo/khamrah-dukhan.jpg","etiqueta":"Nuevo"},
    {"codigo":"MEL-L017","nombre":"ART OF UNIVERSE","categoria":"Lujo","descripcion":"Cítricos frescos, flores blancas, dulzor elegante","precio":100000,"imagen":"imagenes/lujo/art-of-universe.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L018","nombre":"MUSAMAM","categoria":"Lujo","descripcion":"Oud, especias árabes, cuero, ámbar","precio":100000,"imagen":"imagenes/lujo/musamam.jpg","etiqueta":"Exclusivo"},
    {"codigo":"MEL-L019","nombre":"HIS CONFESSION","categoria":"Lujo","descripcion":"Maderas intensas, vainilla, ámbar, especias dulces","precio":100000,"imagen":"imagenes/lujo/his-confession.jpg","etiqueta":"Kit"},
    {"codigo":"MEL-L020","nombre":"KIT DE YARA Y ASAD","categoria":"Lujo","descripcion":"Pimienta negra, tabaco, piña, café, iris, vainilla, ámbar","precio":160000,"imagen":"imagenes/lujo/kit-yara-asad.jpg","etiqueta":"Kit"},
    {"codigo":"MEL-L021","nombre":"IL-MIN FEMME","categoria":"Lujo","descripcion":"Flores blancas, cítricos suaves, almizcle","precio":100000,"imagen":"imagenes/lujo/il-min-femme.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L022","nombre":"IL-MIN KAKUNO","categoria":"Lujo","descripcion":"Cítricos frescos, flores delicadas, almizcle","precio":100000,"imagen":"imagenes/lujo/il-min-kakuno.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L023","nombre":"IL-MIN ROSO","categoria":"Lujo","descripcion":"Rosas intensas, flores rojas, almizcle","precio":100000,"imagen":"imagenes/lujo/il-min-roso.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L024","nombre":"OUD SAFFRON","categoria":"Lujo","descripcion":"Oud, azafrán, especias orientales, ámbar","precio":100000,"imagen":"imagenes/lujo/oud-saffron.jpg","etiqueta":"Premium"},
    {"codigo":"MEL-L025","nombre":"VELVET GOLD","categoria":"Lujo","descripcion":"Pachulí, polvo atalcado, dulzor ambarado","precio":100000,"imagen":"imagenes/lujo/velvet-gold.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L026","nombre":"ORIENTICA ROJA","categoria":"Lujo","descripcion":"Cítricos, maderas, especias intensas","precio":100000,"imagen":"imagenes/lujo/orientica-roja.jpg","etiqueta":"Premium"},
    {"codigo":"MEL-L027","nombre":"EMEER","categoria":"Lujo","descripcion":"Cítricos, madera aromática, ámbar","precio":100000,"imagen":"imagenes/lujo/emeer.jpg","etiqueta":"Premium"},
    {"codigo":"MEL-L028","nombre":"AMBER OUD GOLD","categoria":"Lujo","descripcion":"Ámbar dorado, vainilla, especias suaves","precio":100000,"imagen":"imagenes/lujo/amber-oud-gold.jpg","etiqueta":"Premium"},
    {"codigo":"MEL-L029","nombre":"AMBER ULTRA VIOLET","categoria":"Lujo","descripcion":"Ámbar, flores violetas, dulzor sofisticado","precio":100000,"imagen":"imagenes/lujo/amber-ultra-violet.jpg","etiqueta":"Premium"},
    {"codigo":"MEL-L030","nombre":"SHAHEEN GOLD","categoria":"Lujo","descripcion":"Dulzor elegante, especias suaves, ámbar","precio":100000,"imagen":"imagenes/lujo/shaheen-gold.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L031","nombre":"SHAHEEN SILVER","categoria":"Lujo","descripcion":"Frescor cítrico, especias ligeras, madera blanca","precio":100000,"imagen":"imagenes/lujo/shaheen-silver.jpg","etiqueta":"Lujo"},
    {"codigo":"MEL-L032","nombre":"HAYA","categoria":"Lujo","descripcion":"Flores dulces, jazmín, vainilla, ámbar","precio":100000,"imagen":"imagenes/lujo/haya.jpg","etiqueta":"Popular"},
    {"codigo":"MEL-L033","nombre":"AJWAD","categoria":"Lujo","descripcion":"Frutas tropicales, dulzor avainillado, ámbar","precio":100000,"imagen":"imagenes/lujo/ajwad.jpg","etiqueta":"Divertido"},
    {"codigo":"MEL-L034","nombre":"YUM YUM","categoria":"Lujo","descripcion":"Gourmand dulce, vainilla, caramelo","precio":100000,"imagen":"imagenes/lujo/yum-yum.jpg","etiqueta":"Verano"},
    {"codigo":"MEL-L035","nombre":"ISLAND BLISS BREEZER","categoria":"Lujo","descripcion":"Frutas tropicales, coco, flores exóticas","precio":100000,"imagen":"imagenes/lujo/island-bliss-breezer.jpg","etiqueta":"Exótico"},
    {"codigo":"MEL-L036","nombre":"ISLAND BLISS","categoria":"Lujo","descripcion":"Frutas tropicales, coco, flores exóticas","precio":100000,"imagen":"imagenes/lujo/island-bliss.jpg","etiqueta":"Exótico"},
    {"codigo":"MEL-L037","nombre":"VANILLA FREAK","categoria":"Lujo","descripcion":"Vainilla intensa, tonka, caramelo","precio":110000,"imagen":"imagenes/lujo/vanilla-freak.jpg","etiqueta":"Gourmand"},
    {"codigo":"MEL-L038","nombre":"MALLOW MADNESS","categoria":"Lujo","descripcion":"Marshmallow, vainilla, azúcar glas","precio":110000,"imagen":"imagenes/lujo/mallow-madness.jpg","etiqueta":"Gourmand"},
    {"codigo":"MEL-L039","nombre":"BERRY ON TOP","categoria":"Lujo","descripcion":"Frutos rojos, frambuesa, grosella negra, vainilla","precio":110000,"imagen":"imagenes/lujo/berry-on-top.jpg","etiqueta":"Gourmand"},
    {"codigo":"MEL-L040","nombre":"COOKIE GRAVE","categoria":"Lujo","descripcion":"Galleta dulce, vainilla, cacao","precio":110000,"imagen":"imagenes/lujo/cookie-grave.jpg","etiqueta":"Gourmand"},
    {"codigo":"MEL-L041","nombre":"WHIPPED PLEASURE","categoria":"Lujo","descripcion":"Crema batida, vainilla, caramelo suave","precio":110000,"imagen":"imagenes/lujo/whipped-pleasure.jpg","etiqueta":"Gourmand"}
];
